const AppDom = {
  uploadInput: document.getElementById("upload-input"),
  uploadBox: document.querySelector(".upload-box"),
  fileSearch: document.getElementById("file-search"),
  fileSearchClear: document.getElementById("file-search-clear"),
  sidebarFileList: document.getElementById("sidebar-file-list"),
  sidebarFileEmpty: document.getElementById("sidebar-file-empty"),
  fileCount: document.getElementById("file-count"),
  saveBtn: document.getElementById("save-btn"),
  exportBtn: document.getElementById("export-btn"),
  breadcrumb: document.querySelector(".breadcrumb-current"),
  contentFilename: document.querySelector(".content-filename"),
  previewPanel: document.getElementById("preview-panel"),
  preview: document.getElementById("preview"),
  tabPreview: document.getElementById("tab-preview"),
  tabEdit: document.getElementById("tab-edit"),
  rulesPanel: document.getElementById("rules-panel"),
  rulesTree: document.getElementById("rules-tree"),
  conditionsPanel: document.getElementById("conditions-panel"),
  conditionsList: document.getElementById("conditions-list"),
  saveRulesBtn: document.getElementById("save-rules-btn"),
  redetectRulesBtn: document.getElementById("redetect-rules-btn"),
  addRuleBtn: document.getElementById("add-rule-btn"),
  statusText: document.getElementById("status-text"),
  statusEncoding: document.getElementById("status-encoding"),
};
